### ISSUE TITLE
Random Episode plays the same episode

### ISSUE THREAD

**Issue by esarella** [plexinc-plugins/South-Park.bundle#15]
When Random episode is clicked only one episode is played ad nauseum. I have to exit the channel and load it again to play a different random episode. 

RANDOM_URL = '%s/full-episodes/random' % (BASE_URL) is persisted and needs to be flushed and reloaded whenever RandomEpisode() is called

**Comment by sander1** [comment]
It looks like some clients do not see or respect the `no_cache=True` set on the ObjectContainer.
