### ISSUE TITLE
Channel No Longer Works on Version 0.9.15.6.1714-7be11e1  Feb 23, 2016

### ISSUE THREAD

**Issue by slamanna212** [plexinc-plugins/South-Park.bundle#16]
Once you upgrade your plex server to Version 0.9.15.6.1714-7be11e1 
Feb 23, 2016 , this channel no longer works. If you downgrade your plex server to any newer version, it works again

**Comment by sander1** [comment]
If a new PMS version breaks the channel it's probably not a channel issue :-)

**Comment by slamanna212** [comment]
Maybe the plugin should be updated to support the latest server version :)

**Comment by sander1** [comment]
> Maybe the plugin should be updated to support the latest server version :)

That's not how this work :) But newer versions of PMS have fixed the issues.
